on: [push]
jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      resource_group: "mydemorg"
    steps:
    
    # - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS_SP }}

    - name: create a resource if not exists
      run: |
        status=`az group list | grep ${{ env.resource_group }} | wc -l`
        
        if [ $status -eq 0 ]
        then
            az group create --name ${{ env.resource_group }} --location centralindia
        else 
            echo "resource already exists"
        fi


# namespacePresent=`kubectl get namespace | grep anilsdemoaks8cdf | wc -l`
#         if [ $namespacePresent -eq 0 ]
#         then
#             echo `kubectl create namespace anilsdemoaks8cdf`
#         fi