on: [push]
jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      resource_group: "mydemorg"
    steps:
    
    # - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS_SP }}

    - name: create a resource if not exists
      run: |
        az group list | grep ${{ env.resource_group }}
        status="$(echo $?)"
        if [[ status == 0 ]];
        then
            echo "resource already exists"
        else 
            az group create --name ${{ env.resource_group }} --location centralindia
        fi
