name: Terraform-Azure

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_FILE_PATH: az_resource_group

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=${{ env.TF_FILE_PATH }} fmt -check -chdir=az_resource_group/main.tf
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform -chdir=${{ env.TF_FILE_PATH }} init
      
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=${{ env.TF_FILE_PATH }} validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=${{ env.TF_FILE_PATH }} plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        run: terraform -chdir=${{ env.TF_FILE_PATH }} apply -auto-approve -input=false